# Generated by Django 4.2 on 2023-05-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="cloth_selection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.CharField(max_length=100)),
                ("shirt", models.IntegerField(default="")),
                ("Pants", models.IntegerField(default="")),
                ("Jeans", models.IntegerField(default="")),
                ("Towel", models.IntegerField(default="")),
                ("shirt_image", models.ImageField(default="", upload_to="data/media")),
                ("Pants_image", models.ImageField(default="", upload_to="data/media")),
                ("Jeans_image", models.ImageField(default="", upload_to="data/media")),
                ("Towel_image", models.ImageField(default="", upload_to="data/media")),
            ],
        ),
    ]
