# Generated by Django 4.2 on 2023-05-21 18:01
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clothselection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloth_selection",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
