# Generated by Django 4.2 on 2023-05-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clothselection", "0002_cloth_selection_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloth_selection",
            name="profile_image",
            field=models.ImageField(default="", upload_to="data/media"),
        ),
    ]
