# Generated by Django 4.2 on 2023-05-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="cloth_selection_1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.CharField(max_length=100)),
                ("name", models.CharField(default="", max_length=100)),
                ("Jacket", models.IntegerField(default="")),
                ("Blazer", models.IntegerField(default="")),
                ("Hoodie", models.IntegerField(default="")),
                ("Blanket", models.IntegerField(default="")),
                ("jacket_image", models.ImageField(default="", upload_to="data/media")),
                ("blazer_image", models.ImageField(default="", upload_to="data/media")),
                ("hoodie_image", models.ImageField(default="", upload_to="data/media")),
                (
                    "blanket_image",
                    models.ImageField(default="", upload_to="data/media"),
                ),
                ("Total", models.IntegerField(default=0)),
            ],
        ),
    ]
