# Generated by Django 4.2 on 2023-05-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clothselection2", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloth_selection_1",
            name="Total",
            field=models.BigIntegerField(default=0),
        ),
    ]
